adm/urls.py
from django.urls import path
# from admin_volt import views
from adm import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    # Index
    path('', views.index, name="index"),

    # Authentication
    path('accounts/register/', views.UserRegister.as_view(), name="register"),
    path('accounts/login/', views.UserLogin.as_view(), name="login"),
    path('accounts/logout/', views.UserLogout.as_view(), name="logout"),
    path('dashboard/localites/', views.Localites.as_view(), name="localites"),
    # path('dashboard/localites_for_tables2/', views.LocaliteListView.as_view(), name="localitesTables2"),
    path('dashboard/localites/add/', views.AddLocalite.as_view(), name="add_localite"),
    path('dashboard/localites/edit/<pk>/', views.EditLocalite.as_view(), name="edit_localite"),
    
    path('dashboard/localites/search/<query>/', views.SearchTerm.as_view(), name="searchTerm"),
    path('dashboard/localites/search/', views.SearchLocalite.as_view(), name="search_localite"),

    path('dashboard/localites/delete/<pk>/', views.DeleteLocalite.as_view(), name="delete_localite"),
    path('dashboard/localites/get-localite-parent/', views.GetLocaliteParent.as_view(), name="get_localite_parent"),






    path('accounts/password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password-change-done.html'
    ), name="password_change_done"),
    path('accounts/password-reset/', views.UserPasswordResetView.as_view(), name="password_reset"),
    path('accounts/password-reset-confirm/<uidb64>/<token>/',
        views.UserPasswrodResetConfirmView.as_view(), name="password_reset_confirm"
    ),
    path('accounts/password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password-reset-done.html'
    ), name='password_reset_done'),
    path('accounts/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password-reset-complete.html'
    ), name='password_reset_complete'),
    path('accounts/lock/', views.lock, name="lock"),

    # Pages
    path('pages/dashboard/', views.dashboard, name="dashboard"),
    path('pages/transaction/', views.transaction, name="transaction"),
    path('pages/settings/', views.settings, name="settings"),

    # Tables
    path('tables/bs-tables/', views.bs_tables, name="bs_tables"),

    # Components
    path('components/buttons/', views.buttons, name="buttons"),
    path('components/notifications/', views.notifications, name="notifications"),
    path('components/forms/', views.forms, name="forms"),
    path('components/modals/', views.modals, name="modals"),
    path('components/typography/', views.typography, name="typography"),

    # Errors
   path('error/404/', views.error_404, name="error_404"),
   path('error/500/', views.error_500, name="error_500"),

    # Extra
   path('pages/upgrade-to-pro/', views.upgrade_to_pro, name="upgrade_to_pro"),
]

ehouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('catalog/', include('catalog.urls')),
    path('adm/', include('adm.urls'))
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import UserRegister, UserLogin, UserActivateAccount, UserLogout, UserPasswordForget, UserActivateResetpassword, UserResetPassword

urlpatterns = [
    path('register/', UserRegister.as_view(), name='user-register'),
    path('activate/<uidb64>/<token>/', UserActivateAccount.as_view(), name='user-activate-account'),
    path('login/', UserLogin.as_view(), name='user-login'),
    path('logout/', UserLogout.as_view(), name='user-logout'),
    path('forget-password/', UserPasswordForget.as_view(), name='user-password-forget'),
    path('user-resetpassword-validate/<uidb64>/<token>/', UserActivateResetpassword.as_view(), name='user-resetpassword-validate'),
    path('user-resetpassword/', UserResetPassword.as_view(), name='user-resetpassword'),
]

user/models.py
from django.contrib.auth.hashers import make_password
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')
        if not username:
            raise ValueError('User must have an username')
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=make_password(password),
        )
        # user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            # password=password,
            password=make_password(password),
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    first_name = models.CharField(max_length=250, blank=False, null=False)
    last_name = models.CharField(max_length=250, blank=False, null=False)
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)
    password = models.CharField(max_length=128)

    # required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_joined = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.email

    # this methods are require to login super user from admin panel
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # this methods are require to login super user from admin panel
    def has_module_perms(self, add_label):
        return True
        
        
# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     follows = models.ManyToManyField(
#         "self", related_name="followed_by", symmetrical=False, blank=True
#     )

#     def __str__(self):
#         return self.user.username

user/forms.py
from django import forms
from .models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
       #  'class': 'input is-info',
       'class': 'form-control'
    }))

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        # 'class': 'input is-info',
       'class': 'form-control'
    }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username','phone_number', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter phone number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter email'
        self.fields['username'].widget.attrs['placeholder'] = 'Enter username'

        self.fields['first_name'].error_messages = {'required': 'Entrer un nom'}
        self.fields['last_name'].error_messages = {'required': 'Entrer un prénom'}
        self.fields['username'].error_messages = {'required': 'Entrer un petit nom'}
        self.fields['email'].error_messages = {'required': 'Entrer un email'}
        self.fields['phone_number'].error_messages = {'required': 'Entrer un numero pour vous contacter'}
        self.fields['password'].error_messages = {'required': 'Entrer un mot de passe'}
        self.fields['confirm_password'].error_messages = {'required': 'Confirmer mot de passe'}

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(UserRegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match."
            )




class UserForgetPasswordForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Entrer un email',
        'class': 'input is-dark',
         }),
        error_messages={
            'required': "Password can't be null",
            'invalid': 'Please enter a valid email address.'
        })


    def clean(self):
        email = self.cleaned_data.get('email')
        if email is not None:
            if not User.objects.filter(email= email).exists():
                self.add_error('email', "Bad Email")            
        # if(not user):
        #     raise forms.ValidationError("Email don't exist")
        # regex = '^[a-z0-9]+[\.-_]?[a-z0-9]+[@]\w+[.]\w{2,3}$'
        # if not (re.fullmatch(regex, email)):
        #     raise forms.ValidationError("Votre email n'a pas le bon format, veuillez saisir un email valide")
        # return email




class UserResetPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'input is-info',
    }),
    error_messages={
        'required': "Password can't be null",
        'invalid': 'Please enter a valid email address.'
    })

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'input is-info',
    }))

    def clean(self):
        cleaned_data = super(UserResetPasswordForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match."
            )

user/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.hashers import make_password 
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.http import HttpResponse
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import UserRegistrationForm, UserForgetPasswordForm, UserResetPasswordForm
from .models import User
from user import signals

class UserRegister(View):
    form_class = UserRegistrationForm
    template_name = 'user/user_register.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = UserRegistrationForm(request.POST) 
        if form.is_valid(): 
            user_instance = User(
                first_name = form.cleaned_data['first_name'],
                last_name = form.cleaned_data['last_name'],
                username = form.cleaned_data['username'],
                phone_number = form.cleaned_data['phone_number'],
                email = form.cleaned_data['email'],
                password = make_password(form.cleaned_data['password'])
                )
            user_instance.request = request
            user_instance.save()
            messages.success(request, 'Your account is created successfully. We have sent you a verification email to verify your email. Follow the instruction in this email.')   
            to_email =form.cleaned_data['email']
            return redirect('/user/login/?command=verification&email='+to_email)
        return render(request, self.template_name, {'form': form})




class UserLogin(View):
    template_name = 'user/user_login.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        try:
            user_name = User.objects.get(username=username)
        except User.DoesNotExist:
            user_name = User.objects.get(email=username)
        user = auth.authenticate(username=user_name, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            messages.success(request, 'Login successfully')
            return redirect(reverse('home'))
        messages.error(request, 'Invalid credentials, please check username/email or password.')
        return render(request, self.template_name)




class UserActivateAccount(View):
    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User._default_manager.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Congratulations! Your account is activated.')
            return redirect(reverse('user-login'))




class UserLogout(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        auth.logout(request)
        messages.success(request, 'You are logged out.')
        return redirect('/home/')




class UserPasswordForget(View):
    form_class = UserForgetPasswordForm
    template_name = 'user/user_password_forget.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = UserForgetPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            user = User.objects.get(email=email)
            signals.user_password_reset_email.send(sender=self.__class__, user=user, request=request)
            messages.success(request, 'We have sent you an reset password link to your mail. Follow the instruction in this email.')
            return redirect('/user/login/?command=reset-password&email='+email)
        return render(request, self.template_name, {'form': form})




class UserActivateResetpassword(View):  
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User._default_manager.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            request.session['uid'] = uid
            messages.success(request, 'Please reset your password')
            return redirect(reverse('user-resetpassword'))
        else:
            messages.error(request, 'This link has been expired!')
            return redirect(reverse('login'))




class UserResetPassword(View):
    form_class = UserResetPasswordForm
    template_name = 'user/user_reset_password.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = UserResetPasswordForm(request.POST)
        if form.is_valid():
            password = make_password(form.cleaned_data.get('password'))
            uid = request.session.get('uid')
            user = User.objects.get(pk=uid)
            user.password = password
            user.save()
            messages.success(request, 'Password resetting successfully!')
            return redirect('/user/login/')
        return render(request, self.template_name, {'form': form})

user/templates/user/user_login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Ehouse Login {% endblock %}

{% block content %}
	
<div class="hero is-fullheight">
    <div class="hero-body is-justify-content-center is-align-items-center is-flex is-flex-direction-column">
        <div class="columns is-flex is-flex-direction-column">
            
            <div class="has-text-centered column is-8">
                {% include 'includes/messages.html' %}
            </div>

            <form action="{% url 'user-login' %}" method="POST" novalidate>
				<div class="has-text-centered column is-8">
					  <ion-icon name="person-add-sharp" size="large"></ion-icon>
					  <p class="is-size-3 has-text-weight-bold">Welcome back</p>
				</div>
            {% csrf_token %}
                <div class="column">
                    <label for="id_username">Email or username</label>
                    <input class="input is-dark" name="username" type="text" placeholder="Email or username" id="id_username">
                </div>
                <div class="column">
                    <label for="id_password">Password</label>
                    <input class="input is-dark" type="password" name="password" placeholder="Password" id="id_password">
                    <a href="{% url 'user-password-forget' %}" class="is-size-7 has-text-dark has-text-weight-bold">forget password?</a>
                </div>
                <div class="column">
                    <button class="button is-dark is-fullwidth" type="submit">Login</button>
                </div>
                <div class="has-text-centered">
                    <p class="is-size-7">Don't have an account?<a href="{% url 'user-register' %}" class="has-text-dark has-text-weight-bold"> Sign up</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>
    
{% endblock %}

user/templates/user/user_password_forget.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Ehouse Reset Password {% endblock %}

{% block content %}

<div class="hero is-fullheight">
    <div class="hero-body is-justify-content-center is-align-items-center is-flex is-flex-direction-column">
        <div class="columns is-flex is-flex-direction-column">
            
            <div class="has-text-centered column is-8">
                {% include 'includes/messages.html' %}
            </div>

            <form action="{% url 'user-password-forget' %}" method="POST" novalidate>
                {% csrf_token %}
                <div class="has-text-centered column is-8">
                    <ion-icon name="person-add-sharp" size="large"></ion-icon>
                    <p class="is-size-3 has-text-weight-bold">Reset Password</p>
                </div>
                <div class="column">
                    {% if form.email.errors %}
                        <div class="help is-danger">{{ form.email.errors }}</div>
                    {% endif %}
                    {{ form.email.label }}
                    {{ form.email }}
                </div>
                <div class="column">
                    <button class="button is-dark is-fullwidth" type="submit">Reset password Email</button>
                </div>
                <div class="has-text-centered">
                    <p class="is-size-7">Do you remember your password <a href="{% url 'user-login' %}" class="has-text-dark has-text-weight-bold"> Log in</a>
                    </p>
                    <p class="is-size-7">Don't have an account? <a href="{% url 'user-register' %}" class="has-text-dark has-text-weight-bold"> Signup</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

user/templates/user/user_register.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Ehouse Register an account {% endblock %}

{% block content %}

      <div class="hero is-fullheight">
        <div class="hero-body is-justify-content-center is-align-items-center is-flex is-flex-direction-column">
          <div class="columns is-flex is-flex-direction-column column">
			<form method="POST" action="{% url 'user-register'%}" novalidate>
				<div class="has-text-centered column is-8">
					  <ion-icon name="person-add-sharp" size="large"></ion-icon>
					  <p class="is-size-3 has-text-weight-bold">Register your account</p>
				</div>
			{% csrf_token %}
				<div class="column is-8">
					<label for="id_last_name">Lastname</label>
					{{form.last_name}}
					{% if form.last_name.errors %}
						<div class="help is-danger">{{ form.last_name.errors }}</div>
					{% endif %}
				</div>
				<div class="column is-8">
					<label for="id_first_name">Firstname</label>
					{{form.first_name}}
					{% if form.last_name.errors %}
						<div class="help is-danger">{{ form.first_name.errors }}</div>
					{% endif %}
				</div>
				<div class="column is-8">
					<label for="id_username">Username</label>
					{{form.username}}
					{% if form.username.errors %}
						<div class="help is-danger">{{ form.username.errors }}</div>
					{% endif %}
				</div>
				<div class="column is-8">
					<label for="id_email">Email</label>
					{{form.email}}
					{% if form.email.errors %}
						<div class="help is-danger">{{ form.email.errors }}</div>
					{% endif %}
				</div>
					<div class="column is-8">
					<label for="id_phone_number">Phone_number</label>
					{{form.phone_number}}
					{% if form.phone_number.errors %}
						<div class="help is-danger">{{ form.phone_number.errors }}</div>
					{% endif %}
				</div>
				<div class="column is-8">
					<label for="id_password">Password</label>
					{{form.password}}
					{% if form.password.errors %}
						<div class="help is-danger">{{ form.password.errors }}</div>
					{% endif %}
				</div>

				<div class="column is-8">
					<label for="id_password">Confirm password</label>
					{{form.confirm_password}}
					{% if form.non_field_errors %}
						<div class="help is-danger">{{ form.non_field_errors }}</div>
					{% endif %}
					<input type="checkbox">
						I agree to the <a href="#" class="has-text-dark has-text-weight-bold">terms and conditions</a>
				</div>

				
				<div class="column is-8 is-8">
					<button class="button is-dark is-fullwidth" type="submit">Create an account</button>
				</div>
				<div class="has-text-centered column is-8">
					<p> Already have an account?  <a href="{% url 'user-login' %}" class="has-text-dark has-text-weight-bold">Login</a></p>
				</div>
			</form>
          </div>
        </div>
      </div>
    
{% endblock %}

user/templates/user/user_reset_password.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Ehouse Register an account {% endblock %}

{% block content %}

      <div class="hero is-fullheight">
        <div class="hero-body is-justify-content-center is-align-items-center is-flex is-flex-direction-column">
          <div class="columns is-flex is-flex-direction-column column">

						<div class="has-text-centered column is-8">
							{% include 'includes/messages.html'%}
						</div>
						
			<form method="POST" action="{% url 'user-resetpassword'%}" novalidate>
				<div class="has-text-centered column is-8">
					  <ion-icon name="person-add-sharp" size="large"></ion-icon>
					  <p class="is-size-3 has-text-weight-bold">Reset Your Password</p>
				</div>

				<div class="column is-8">
					{% if form.non_field_errors %}
						<div class="help is-danger">{{ form.non_field_errors }}</div>
					{% endif %}
				</div>

			{% csrf_token %}
				<div class="column is-8">
					<label for="id_password">Password</label>
					{{form.password}}
					{% if form.password.errors %}
						<div class="help is-danger">{{ form.password.errors }}</div>
					{% endif %}
				</div>

				<div class="column is-8">
					<label for="id_password">Confirm password</label>
					{{form.confirm_password}}
				</div>

				
				<div class="column is-8 is-8">
					<button class="button is-dark is-fullwidth" type="submit">Reset</button>
				</div>
        <div class="has-text-centered column is-8">
            <p class="is-size-7">Do you remember your password <a href="{% url 'user-login' %}" class="has-text-dark has-text-weight-bold"> Log in</a>
            </p>
            <p class="is-size-7">Don't have an account? <a href="{% url 'user-register' %}" class="has-text-dark has-text-weight-bold"> Signup</a>
            </p>
        </div>
			</form>
          </div>
        </div>
      </div>
    
{% endblock %}